- name: create user
  tags: always
  ansible.builtin.user:
    name: simone
    groups: root

- name: add sudoers file for simone
  tags: always
  ansible.builtin.copy:
    src: sudoer_simone
    dest: /etc/sudoers.d/simone
    owner: root
    group: root
    mode: 0440

- name: add ssh key for simone user
  tags: always
  ansible.builtin.authorized_key:
    user: simone
    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDNw/3oBH7hd4koUt4qH4/4VUsXlnaW7w/77uWqUVSoU6hGaefti02QhO1TGcW0zvVjBb7SMZxFa/jU9TcxsQzRMgtBKR5mum0b9yVvgrseumKyjm/7C9zeiKtnLMPwfGM+E4lEPhGt9XGbOrIXWGDRoBdK50BT8u7mNLiCzURTzsXZzZuEy+noxzIPyuxXqVJPfnUoSpTEC/dd3kHUfkh/zR0Ky6oGkqnEH69RG5RQ1vJiKLFFW13OwkRK9Us61zcZbWb/pA6CJSFalyJA1ySZ+rIHA7YhZrgOo/kh9U5yYXfAkSpoVt40UTcKBwJE6GHbbVcOUNRQMT96tr9S3bJzcdvb7DWdGajXbI2sE2eW8rL6/mnLrEpKQb9YG6IkVPWQ21/06Z0tgCXLkgy6VN9tcNBt8zHaU+cpn5tBOeR7vadsjbMlKQV1oMaJ29BDtDMYaWh4K3lOniUNeqE3qkE1Q/7+cI24ZQhcoXO/Xl9BIsNLF7r5DWx3zSmbKPmJdAU= vagrant@controlplane"
